### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [nethical6/digipaws#58]
The apk url is expected to be https://github.com/nethical6/digipaws/releases/download/1.3-alpha-lite/app-lite-universal-release-unsigned-signed.apk but the tag name is 1.3-alpha. Could you please change the tag name or change the version name? Thanks!

**Comment by nethical6** [comment]
sure!

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
@nethical6 your Tag and versioName don't match: https://github.com/nethical6/digipaws/releases/tag/2.1-alpha

ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/9191784847#L418

**Comment by nethical6** [comment]
i just updated the tag again .
sorry for repeating the same mistake :(

**Comment by licaon-kter** [comment]
thanks
