### ISSUE TITLE
Feature request: Automatically start/end focus mode at a given time of day?

### ISSUE THREAD

**Issue by aria-dos** [nethical6/digipaws#59]
Hello! I was wondering if there is a way to automatically enable focus mode at a given time of day. Is this possible to implement? Or does this fall outside of the scope of this app? I'm imagining it working similar to the scheduled Do Not Disturb mode.

**Comment by nethical6** [comment]
sure, I'll add it in a few days

**Comment by nethical6** [comment]
Thanks for the idea! try it out -> https://github.com/nethical6/digipaws/actions/runs/12542806180

**Comment by aria-dos** [comment]
have been using this for a while now and wanna say it works really well! thank you for implementing this so quickly!
